on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Docker Build
        run: docker build -t luisferlcc/412-music-api:latest .

      - name: Docker Push
        run: docker push luisferlcc/412-music-api:latest
